### ISSUE TITLE
== Compilation error in file test/node_modules/phoenix/priv/templates/phx.gen.channel/channel_test.exs ==

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-phoenix-framework#129]
Full error:
```
== Compilation error in file test/node_modules/phoenix/priv/templates/phx.gen.channel/channel_test.exs ==
** (SyntaxError) test/node_modules/phoenix/priv/templates/phx.gen.channel/channel_test.exs:1: syntax error before: '='
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/kernel/parallel_compiler.ex:211: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```
The file in question:
```
test/node_modules/phoenix/priv/templates/phx.gen.channel/channel_test.exs ==
```
contains:
```elixir
defmodule <%= inspect context.module %>Test do
  use <%= inspect context.base_module %>.DataCase

  alias <%= inspect context.module %>
end
```

I don't _understand_ why `node_modules` would end up in `/test` ...
None of our other Phoenix projects appear to have them.

**Comment by nelsonic** [comment]
deleted `test/node_modules`.
tests run.
