### ISSUE TITLE
What are Phoenix contexts

### ISSUE THREAD

**Issue by SimonLab** [dwyl/learn-phoenix-framework#137]
Contexts have been added with Phoenix 1.3:
https://www.phoenixframework.org/blog/phoenix-1-3-0-released
![image](https://user-images.githubusercontent.com/6057298/80506082-08c83300-896d-11ea-8906-2d573196f6f6.png)

see also the elixirCasts' video:
[![image](https://user-images.githubusercontent.com/6057298/80506219-31502d00-896d-11ea-997f-cafd29284507.png)](https://elixircasts.io/phoenix-contexts)

**Comment by nelsonic** [comment]
Revisiting `contexts` in `Phoenix 1.8` to see if they are worth using: https://hexdocs.pm/phoenix/1.8.0/contexts.html

<img width="1375" height="1025" alt="Image" src="https://github.com/user-attachments/assets/0ab430b4-e8ad-4c64-8369-10d68cf78363" />

**Comment by nelsonic** [comment]
Re-watched the `ElixirCasts` video in the OP and while it's _good_ it doesn't explain why we _need_ `contexts` ... 💭

**Comment by nelsonic** [comment]
Skip the `context`:  
<img width="1447" height="712" alt="Image" src="https://github.com/user-attachments/assets/7d302a3e-505b-4777-bf81-2c5329bafed9" />

It's not just in an "unknown" domain ... 
`contexts` may "help organise code" in a _massive_ codebase.
But in a _small_ one, they just add a layer of complexity and more files. 🙃

**Comment by nelsonic** [comment]
Tomorrow: https://hexdocs.pm/phoenix/1.8.0/in_context_relationships.html

**Comment by nelsonic** [comment]
Getting: 

```sh
== Compilation error in file lib/hello/catalog.ex ==
** (Kernel.TypespecError) lib/hello/catalog.ex:95: expected key-value pairs in struct Hello.Catalog.Product
    (elixir 1.18.4) lib/kernel/typespec.ex:980: Kernel.Typespec.compile_error/2
    (stdlib 7.0.2) lists.erl:2673: :lists.mapfoldl_1/3
    (elixir 1.18.4) lib/kernel/typespec.ex:392: Kernel.Typespec.translate_spec/8
    (stdlib 7.0.2) lists.erl:2673: :lists.mapfoldl_1/3
    (elixir 1.18.4) lib/kernel/typespec.ex:236: Kernel.Typespec.translate_typespecs_for_module/2
Compiling 1 file (.ex)
```

**Comment by nelsonic** [comment]
```sh
warning: incompatible types given to Ecto.Changeset.get_change/3:

    Ecto.Changeset.get_change(changeset, :categories, [])

given types:

    (
      dynamic(%{
        ...,
        changeset: %Ecto.Changeset{
          action: term(),
          changes: term(),
          constraints: term(),
          data: term(),
          empty_values: term(),
          errors: term(),
          filters: term(),
          params: term(),
          prepare: term(),
          repo: term(),
          repo_opts: term(),
          required: term(),
          types: term(),
          valid?: term(),
          validations: term()
        }
      }),
      :categories,
      empty_list()
    )

but expected one of:

    (
      dynamic(%Ecto.Changeset{
        action: term(),
        changes: term(),
        constraints: term(),
        data: term(),
        empty_values: term(),
        errors: term(),
        filters: term(),
        params: term(),
        prepare: term(),
        repo: term(),
        repo_opts: term(),
        required: term(),
        types: term(),
        valid?: term(),
        validations: term()
      }),
      dynamic(),
      dynamic()
    )

where "changeset" was given the type:

    # type: dynamic(%{..., changeset: %Ecto.Changeset{}})
    # from: lib/hello_web/controllers/product_html/product_form.html.heex:16:21
    (%{changeset: %Ecto.Changeset{}} = _) = changeset

└─ lib/hello_web/controllers/product_html/product_form.html.heex:19:25: HelloWeb.ProductHTML."category_opts (overridable 1)"/1
```

**Comment by nelsonic** [comment]
Working: 
<img width="1152" height="783" alt="Image" src="https://github.com/user-attachments/assets/57fe7714-ef44-43b8-a150-97f672ec74b0" />
