### ISSUE TITLE
web/controllers/video_controller.ex:23: undefined function video_path/2

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-phoenix-framework#30]
on page 93 of Programming Phoenix we run `mix ecto.migrate` ...
we're seeing:

```
== Compilation error on file web/controllers/video_controller.ex ==
** (CompileError) web/controllers/video_controller.ex:23: undefined function video_path/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

![image](https://cloud.githubusercontent.com/assets/194400/22866390/be20a782-f16d-11e6-899a-401367770cff.png)

**Comment by nelsonic** [comment]
The issue was that I skipped the step of adding the resource to the browser scope in `web/router.ex`:
```
resources "/videos", VideoController
```

Once that was done, the `mix ecto.migrate` worked fine. 👍

**Comment by nelsonic** [comment]
Now getting:
![image](https://cloud.githubusercontent.com/assets/194400/22873813/3acba40c-f1ba-11e6-8219-14100d40428b.png)

```
== Compilation error on file web/views/video_view.ex ==
** (CompileError) web/views/video_view.ex:2: module Rumbl.Router.Helpers is not loaded and could not be found
    expanding macro: Rumbl.Web.__using__/1
    web/views/video_view.ex:2: Rumbl.VideoView (module)
    (elixir) expanding macro: Kernel.use/2
    web/views/video_view.ex:2: Rumbl.VideoView (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```
or
```
== Compilation error on file web/views/session_view.ex ==
** (CompileError) web/views/session_view.ex:2: module Rumbl.Router.Helpers is not loaded and could not be found
    expanding macro: Rumbl.Web.__using__/1
    web/views/session_view.ex:2: Rumbl.SessionView (module)
    (elixir) expanding macro: Kernel.use/2
    web/views/session_view.ex:2: Rumbl.SessionView (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by nelsonic** [comment]
Major [PEBKAC](https://en.wikipedia.org/wiki/User_error) ...!! (_or unclear instructions in the book... but I prefer that I didn't read them fully..._)

running `mix ecto.migrate` ***too soon*** means that the DB table gets created before all code changes have been made ... that means you cannot run it again so compilation fails!!

Read through ***ALL*** the instructions on Pages 92 - 95 ***before*** running `mix ecto.migrate` then it will all work fine. 👍

**Comment by nelsonic** [comment]
Totes works:
![image](https://cloud.githubusercontent.com/assets/194400/22875020/3d5271ae-f1c1-11e6-9d1a-471de0f84c1f.png)

Added video:
![image](https://cloud.githubusercontent.com/assets/194400/22875038/5083cc50-f1c1-11e6-920f-e1e9dc9d14e7.png)
