### ISSUE TITLE
warning: using conn/0 to build a connection is deprecated. Use build_conn/0 instead

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-phoenix-framework#36]
```
warning: using conn/0 to build a connection is deprecated. Use build_conn/0 instead.
    test/controllers/video_controller_test.exs:31: Rumbl.VideoControllerTest.__ex_unit_setup_1/1
    test/controllers/video_controller_test.exs:1: Rumbl.VideoControllerTest.__ex_unit__/2
    (ex_unit) lib/ex_unit/runner.ex:289: ExUnit.Runner.exec_test_setup/2
    (ex_unit) lib/ex_unit/runner.ex:247: anonymous fn/2 in ExUnit.Runner.spawn_test/3
```

**Comment by nelsonic** [comment]
changing 
```
conn = assign(conn(), :current_user, user)
```
to:
```
conn = assign(build_conn, :current_user, user)
```
did the trick.
