### ISSUE TITLE
p.168 attempting to create a video in iex get ** (KeyError) key :slug not found in: %Rumbl.Video{__meta__: #Ecto.Schema.Metadata<:built, "videos">

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-phoenix-framework#51]
On page 168 of Programming Phoenix the instruction is to create a video.
but when I _attempt_ to run the command listed in the book 
```
iex(1)> video = %Rumbl.Video{id: 1, slug: "hello"}
```
I get the an error ... 😞 

Stack trace:
```
** (KeyError) key :slug not found in: %Rumbl.Video{__meta__: #Ecto.Schema.Metadata<:built, "videos">, category: #Ecto.Association.NotLoaded<association :category is not loaded>, category_id: nil, description: nil, id: 1, inserted_at: nil, title: nil, updated_at: nil, url: nil, user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_id: nil}
    (stdlib) :maps.update(:slug, "hello", %Rumbl.Video{__meta__: #Ecto.Schema.Metadata<:built, "videos">, category: #Ecto.Association.NotLoaded<association :category is not loaded>, category_id: nil, description: nil, id: 1, inserted_at: nil, title: nil, updated_at: nil, url: nil, user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_id: nil})
     (rumbl) web/models/video.ex:4: anonymous fn/2 in Rumbl.Video.__struct__/1
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
     (rumbl) expanding struct: Rumbl.Video.__struct__/1
             iex:1: (file)
```
Screenshot:
![image](https://cloud.githubusercontent.com/assets/194400/23586865/6a8b4f76-0196-11e7-895e-d179d8561d14.png)

**Comment by nelsonic** [comment]
Just checked and Creating videos isn't working in the UI either:
![image](https://cloud.githubusercontent.com/assets/194400/23586895/0f1c5c88-0197-11e7-95cf-f2eba52bb699.png)

**Comment by nelsonic** [comment]
Re-running ` mix run priv/repo/seeds.exs` to create the categories meant that I can create videos:
![image](https://cloud.githubusercontent.com/assets/194400/23587146/22f8e666-019e-11e7-9d5f-4e6cd7e87b42.png)

But still have the `defimpl` issue: #52

**Comment by nelsonic** [comment]
Seriously though, this is getting "_old_"... 
![image](https://cloud.githubusercontent.com/assets/194400/23587174/a07d4c12-019e-11e7-8595-adfd933d0aad.png)

**Comment by nelsonic** [comment]
obviously it wasn't going to work until I added the slug to the videos model... duh!
